import type { GraphData } from '../src';

export const smallGraph: GraphData = {
  nodes: {
    'n1': { id: 'n1', names: ['Metformin'], types: ['biolink:Drug'] },
    'n2': { id: 'n2', names: ['Type 2 Diabetes'], types: ['biolink:Disease'] },
    'n3': { id: 'n3', names: ['AMP-activated Protein Kinase'], types: ['biolink:Protein'] },
    'n4': { id: 'n4', names: ['Glucose'], types: ['biolink:ChemicalEntity'] },
    'n5': { id: 'n5', names: ['Insulin Resistance'], types: ['biolink:PhenotypicFeature'] },
    'n6': { id: 'n6', names: ['PRKAB1'], types: ['biolink:Gene'] },
    'n7': { id: 'n7', names: ['Liver'], types: ['biolink:AnatomicalEntity'] },
    'n8': { id: 'n8', names: ['Obesity'], types: ['biolink:Disease'] },
  },
  edges: {
    'e1': { id: 'e1', subject: 'n1', object: 'n2', predicate: 'biolink:treats' },
    'e2': { id: 'e2', subject: 'n1', object: 'n3', predicate: 'biolink:activates' },
    'e3': { id: 'e3', subject: 'n3', object: 'n4', predicate: 'biolink:regulates' },
    'e4': { id: 'e4', subject: 'n5', object: 'n2', predicate: 'biolink:contributes_to' },
    'e5': { id: 'e5', subject: 'n6', object: 'n3', predicate: 'biolink:encodes' },
    'e6': { id: 'e6', subject: 'n1', object: 'n7', predicate: 'biolink:affects' },
    'e7': { id: 'e7', subject: 'n8', object: 'n5', predicate: 'biolink:causes' },
    'e8': { id: 'e8', subject: 'n4', object: 'n7', predicate: 'biolink:located_in' },
    'e9': { id: 'e9', subject: 'n8', object: 'n2', predicate: 'biolink:risk_factor_for' },
  },
};

export const mediumGraph: GraphData = {
  nodes: {
    'n1':  { id: 'n1',  names: ['Ibuprofen'], types: ['biolink:Drug'] },
    'n2':  { id: 'n2',  names: ['Rheumatoid Arthritis'], types: ['biolink:Disease'] },
    'n3':  { id: 'n3',  names: ['COX-2'], types: ['biolink:Protein'] },
    'n4':  { id: 'n4',  names: ['Prostaglandin E2'], types: ['biolink:ChemicalEntity'] },
    'n5':  { id: 'n5',  names: ['Inflammation'], types: ['biolink:PhenotypicFeature'] },
    'n6':  { id: 'n6',  names: ['PTGS2'], types: ['biolink:Gene'] },
    'n7':  { id: 'n7',  names: ['Synovial Joint'], types: ['biolink:AnatomicalEntity'] },
    'n8':  { id: 'n8',  names: ['TNF-alpha'], types: ['biolink:Protein'] },
    'n9':  { id: 'n9',  names: ['IL-6'], types: ['biolink:Protein'] },
    'n10': { id: 'n10', names: ['NF-kB'], types: ['biolink:Protein'] },
    'n11': { id: 'n11', names: ['Naproxen'], types: ['biolink:Drug'] },
    'n12': { id: 'n12', names: ['Osteoarthritis'], types: ['biolink:Disease'] },
    'n13': { id: 'n13', names: ['Pain'], types: ['biolink:PhenotypicFeature'] },
    'n14': { id: 'n14', names: ['Cartilage'], types: ['biolink:AnatomicalEntity'] },
    'n15': { id: 'n15', names: ['Arachidonic Acid'], types: ['biolink:ChemicalEntity'] },
    'n16': { id: 'n16', names: ['COX-1'], types: ['biolink:Protein'] },
    'n17': { id: 'n17', names: ['PTGS1'], types: ['biolink:Gene'] },
    'n18': { id: 'n18', names: ['Stomach'], types: ['biolink:AnatomicalEntity'] },
    'n19': { id: 'n19', names: ['Celecoxib'], types: ['biolink:Drug'] },
    'n20': { id: 'n20', names: ['NFKB1'], types: ['biolink:Gene'] },
  },
  edges: {
    'e1':  { id: 'e1',  subject: 'n1',  object: 'n2',  predicate: 'biolink:treats' },
    'e2':  { id: 'e2',  subject: 'n1',  object: 'n3',  predicate: 'biolink:inhibits' },
    'e3':  { id: 'e3',  subject: 'n3',  object: 'n4',  predicate: 'biolink:produces' },
    'e4':  { id: 'e4',  subject: 'n4',  object: 'n5',  predicate: 'biolink:causes' },
    'e5':  { id: 'e5',  subject: 'n5',  object: 'n2',  predicate: 'biolink:contributes_to' },
    'e6':  { id: 'e6',  subject: 'n6',  object: 'n3',  predicate: 'biolink:encodes' },
    'e7':  { id: 'e7',  subject: 'n2',  object: 'n7',  predicate: 'biolink:affects' },
    'e8':  { id: 'e8',  subject: 'n8',  object: 'n5',  predicate: 'biolink:promotes' },
    'e9':  { id: 'e9',  subject: 'n9',  object: 'n5',  predicate: 'biolink:promotes' },
    'e10': { id: 'e10', subject: 'n10', object: 'n8',  predicate: 'biolink:regulates' },
    'e11': { id: 'e11', subject: 'n10', object: 'n9',  predicate: 'biolink:regulates' },
    'e12': { id: 'e12', subject: 'n11', object: 'n3',  predicate: 'biolink:inhibits' },
    'e13': { id: 'e13', subject: 'n11', object: 'n12', predicate: 'biolink:treats' },
    'e14': { id: 'e14', subject: 'n12', object: 'n14', predicate: 'biolink:affects' },
    'e15': { id: 'e15', subject: 'n13', object: 'n2',  predicate: 'biolink:manifestation_of' },
    'e16': { id: 'e16', subject: 'n13', object: 'n12', predicate: 'biolink:manifestation_of' },
    'e17': { id: 'e17', subject: 'n15', object: 'n3',  predicate: 'biolink:substrate_of' },
    'e18': { id: 'e18', subject: 'n15', object: 'n16', predicate: 'biolink:substrate_of' },
    'e19': { id: 'e19', subject: 'n17', object: 'n16', predicate: 'biolink:encodes' },
    'e20': { id: 'e20', subject: 'n1',  object: 'n18', predicate: 'biolink:affects' },
    'e21': { id: 'e21', subject: 'n19', object: 'n3',  predicate: 'biolink:inhibits' },
    'e22': { id: 'e22', subject: 'n19', object: 'n2',  predicate: 'biolink:treats' },
    'e23': { id: 'e23', subject: 'n20', object: 'n10', predicate: 'biolink:encodes' },
    'e24': { id: 'e24', subject: 'n14', object: 'n7',  predicate: 'biolink:part_of' },
  },
};
