import type { MouseEvent, ReactNode } from 'react';
import type { Node, Edge } from '@xyflow/react';
import type { Padding } from '@xyflow/system';

// Core data types from input schema
export interface GraphData {
  nodes: Record<string, GraphNode>;
  edges: Record<string, GraphEdge>;
  results?: Result[];
  paths?: Record<string, Path>;
  publications?: Record<string, Publication>;
  trials?: Record<string, Trial>;
}

export interface GraphNode {
  id: string;
  names: string[];
  types: string[];
  curies?: string[];
}

export interface GraphEdge {
  id: string;
  subject: string;
  object: string;
  predicate: string;
  predicate_url?: string;
  knowledge_level?: string;
  inferred?: boolean;
  provenance?: Provenance[];
  publications?: { inferred?: Publication[] };
  trials?: Trial[];
  support?: unknown[];
  aras?: string[];
  description?: string;
}

export interface Result {
  id: string;
  drug_name?: string;
  subject: string;
  object: string;
  paths?: string[];
}

export interface Path {
  id: string;
  edges: string[];
}

export interface Publication {
  id: string;
  title?: string;
  authors?: string[];
  year?: number;
  journal?: string;
  pmid?: string;
  doi?: string;
}

export interface Trial {
  id: string;
  title?: string;
  status?: string;
  phase?: string;
  nctid?: string;
}

export interface Provenance {
  source?: string;
  url?: string;
  evidence_type?: string;
}

// Layout types
export type LayoutType = 'hierarchical' | 'hierarchicalLR' | 'force' | 'grid' | 'radial' | 'custom';

export type NodePosition = { x: number; y: number };

export type NodePositionMap = Record<string, NodePosition>;

// Edge path types
export type EdgeType = 'bezier' | 'straight' | 'step' | 'smoothstep';

// Selection types
export interface Selection {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

/** Ids of the elements a delete gesture asked to remove, split by kind. */
export interface DeleteSelection {
  nodes: string[];
  edges: string[];
}

// ReactFlow node/edge data types
export interface GraphNodeData extends Record<string, unknown> {
  label: string;
  graphNode: GraphNode;
  primaryType: string;
  selected?: boolean;
  hovered?: boolean;
  dimmed?: boolean;
}

export interface GraphEdgeData extends Record<string, unknown> {
  label: string;
  graphEdge: GraphEdge;
  edgeType?: EdgeType;
  showLabel?: boolean;
  selected?: boolean;
  inferred?: boolean;
  edgeIndex?: number;
  edgeTotalCount?: number;
  hovered?: boolean;
  dimmed?: boolean;
}

// Annotation types
export interface GraphAnnotation {
  id: string;
  text: string;
  position: { x: number; y: number };
}

export interface GraphAnnotationStyles {
  backgroundColor?: string;
  className?: string;
  deleteButton?: {
    backgroundColor?: string;
    className?: string;
    icon?: ReactNode;
  };
  /**
   * Render URLs, emails, and markdown `[label](url)` links in annotation text as
   * clickable anchors while the annotation is not being edited. Default true.
   */
  linkify?: boolean;
  /** Extra class on the anchors generated by `linkify`. */
  linkClassName?: string;
}

/** Passed to client `nodeChrome` renderers for a single graph node. */
export interface GraphNodeChromeContext {
  node: GraphNode;
  selected: boolean;
  /** Present when GraphView was given `onNodeRemove`. */
  onRemove?: () => void;
  /**
   * Present when GraphView was given `onNodeMenu`.
   * Pointer events use client coordinates; keyboard activation (or a call with
   * no event) falls back to the node's bounding-rect center.
   */
  onMenu?: (event?: MouseEvent) => void;
}

/** Client-provided chrome rendered at the node corners. Hidden until hover. */
export interface GraphNodeChrome {
  topLeft?: (ctx: GraphNodeChromeContext) => ReactNode;
  bottomRight?: (ctx: GraphNodeChromeContext) => ReactNode;
}

/**
 * Client icon for a graph node.
 *
 * `type` is the simplified primary type (e.g. `"Drug"`), not a Biolink CURIE.
 * Full Biolink types are on `node.types`.
 *
 * Return `null` or `undefined` to use the library default, or `false` to hide the icon.
 */
export type GraphNodeIconRenderer = (
  type: string,
  node: GraphNode,
) => ReactNode | null | undefined;

/** Background colors a client can assign to a single graph node. */
export interface GraphNodeColors {
  /** Resting background color. Any CSS color value. */
  background: string;
  /** Background color while hovered. Defaults to `background` when omitted. */
  hoverBackground?: string;
}

/**
 * Client color lookup for a graph node's background.
 *
 * `type` is the simplified primary type (e.g. `"Drug"`), not a Biolink CURIE.
 * Full Biolink types are on `node.types`.
 *
 * Return `null` or `undefined` to leave the node on the library default
 * background, which is what every node uses when no renderer is supplied.
 */
export type GraphNodeColorRenderer = (
  type: string,
  node: GraphNode,
) => GraphNodeColors | null | undefined;

/** Client-configurable hover / dim appearance. Built-in styles remain as defaults. */
export interface GraphHoverStyles {
  /** Opacity applied to dimmed nodes/edges/annotations. Default: 0.3 */
  dimmedOpacity?: number;
  /** Extra class on dimmed nodes */
  dimmedNodeClassName?: string;
  /** Extra class on dimmed edges */
  dimmedEdgeClassName?: string;
  /** Extra class on dimmed annotations */
  dimmedAnnotationClassName?: string;
  /** Extra class on hovered nodes (in addition to built-in) */
  hoveredNodeClassName?: string;
  /** Extra class on hovered edges */
  hoveredEdgeClassName?: string;
  /** Extra class on hovered annotations */
  hoveredAnnotationClassName?: string;
}

export interface GraphAnnotationData extends Record<string, unknown> {
  text: string;
  annotation: GraphAnnotation;
  hovered?: boolean;
  dimmed?: boolean;
}

// ReactFlow typed nodes and edges
export type FlowGraphNode = Node<GraphNodeData, 'graphNode'>;
export type FlowAnnotationNode = Node<GraphAnnotationData, 'graphAnnotation'>;
export type FlowNode = FlowGraphNode | FlowAnnotationNode;
export type FlowEdge = Edge<GraphEdgeData>;

// Hover geometry types
export type HoverAnchorPosition =
  | 'topLeft'    | 'topCenter'    | 'topRight'
  | 'centerLeft' | 'center'       | 'centerRight'
  | 'bottomLeft' | 'bottomCenter' | 'bottomRight'
  | 'midpoint';

export interface HoverGeometry {
  /** Bounding rect of the hovered element in viewport (client) coordinates. */
  rect: { x: number; y: number; width: number; height: number };
  /** The anchor point (in viewport coords) corresponding to the requested HoverAnchorPosition. */
  anchor: { x: number; y: number };
  /** Which anchor position was used to compute `anchor`. */
  anchorPosition: HoverAnchorPosition;
}

/** Imperative viewport focus request; `token` must change on each request. */
export interface GraphFocusRequest {
  nodeId: string;
  token: number;
}

export type FitViewPadding = Padding;

// Component props
export interface GraphViewProps {
  data: GraphData;
  layout?: LayoutType;
  /** Required when `layout` is `'custom'`. Graph-space coordinates for each node id. */
  nodePositions?: NodePositionMap;
  /** Padding when framing the graph via fitView. Default 0.1. */
  fitViewPadding?: FitViewPadding;
  /** Re-frame the viewport when this key changes (e.g. canvas id). */
  viewportSyncKey?: string;
  edgeType?: EdgeType;
  showEdgeLabels?: boolean;
  elkWorkerUrl: string;
  /** Fires when a graph node (not annotation) finishes dragging. Includes all graph-node positions from the current view. */
  onGraphNodeDragStop?: (nodeId: string, position: NodePosition, allPositions: NodePositionMap) => void;
  /** Fires after layout positions are applied: ELK layouts when computation finishes, custom layout when `nodePositions` sync. */
  onLayoutComplete?: (positions: NodePositionMap) => void;
  onSelectionChange?: (selection: Selection) => void;
  /**
   * Fires when Delete or Backspace is pressed with elements selected. The view
   * never removes them itself, so the client stays the single source of truth:
   * drop them from `data` to make the deletion stick.
   *
   * `edges` includes every edge incident to a deleted node, not only the edges
   * the user selected. Unlike `onNodeRemove` (chrome, single node id only), this
   * reports the full multi-selection plus those incident edges.
   */
  onSelectionDelete?: (selection: DeleteSelection) => void;
  onNodeClick?: (node: GraphNode) => void;
  onEdgeClick?: (edge: GraphEdge) => void;
  onNodeHover?: (node: GraphNode | null, geometry: HoverGeometry | null) => void;
  onEdgeHover?: (edge: GraphEdge | null, geometry: HoverGeometry | null) => void;
  /** Fires when an annotation is hovered or unhovered. */
  onAnnotationHover?: (annotationId: string | null) => void;
  hoveredNodeId?: string | null;
  hoveredEdgeId?: string | null;
  hoveredAnnotationId?: string | null;
  nodeHoverAnchor?: HoverAnchorPosition;
  edgeHoverAnchor?: HoverAnchorPosition;
  /**
   * Clear the hover instead of re-measuring its geometry when the viewport pans
   * or zooms. Hover callbacks fire once with `null` at the start of the gesture
   * rather than once per frame, which drops both the per-frame work and the
   * neighborhood dimming while the user is navigating. Hover resumes on the next
   * pointer enter. Default false.
   */
  clearHoverOnViewportChange?: boolean;
  selectedIds?: string[];
  /** Pan/zoom the viewport to frame `nodeId`. Re-triggers when `token` changes. */
  focusRequest?: GraphFocusRequest | null;
  multiEdgeSpacing?: number;
  /** Controlled annotation overlays (graph-space coordinates). */
  annotations?: GraphAnnotation[];
  /** Fires when an annotation is dragged, edited, or deleted. */
  onAnnotationsChange?: (annotations: GraphAnnotation[]) => void;
  /** Client-configurable annotation appearance. */
  annotationStyles?: GraphAnnotationStyles;
  /** Client-configurable hover / dim appearance. */
  hoverStyles?: GraphHoverStyles;
  /** Show the zoomable/pannable minimap. */
  showMiniMap?: boolean;
  /** When false, connection handles stay hidden and are not connectable. Default true. */
  showHandles?: boolean;
  /** Client-rendered chrome at the top-left and bottom-right of each graph node. */
  nodeChrome?: GraphNodeChrome;
  /**
   * Client icon lookup. `type` is the simplified primary type (e.g. `"Drug"`);
   * full Biolink types are on `node.types`. Return `null`/`undefined` for the
   * library default, or `false` to hide the icon.
   */
  getNodeIcon?: GraphNodeIconRenderer;
  /**
   * Client background-color lookup. `type` is the simplified primary type
   * (e.g. `"Drug"`); full Biolink types are on `node.types`. Return
   * `null`/`undefined` to leave the node on the library default background.
   */
  getNodeColor?: GraphNodeColorRenderer;
  /** Fires from node chrome `onRemove`. */
  onNodeRemove?: (nodeId: string) => void;
  /** Fires from node chrome `onMenu` or a node right-click, with the pointer position. */
  onNodeMenu?: (nodeId: string, position: { x: number; y: number }) => void;
  className?: string;
}
